baseURL = 'https://hbjy.dev'
languageCode = 'en-gb'
title = "Hayden's Home"
theme = 'risotto'
paginate = 5

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 2

[params]
  [params.about]
    title = "hayden's home"
    description = "blog of a lowly devops engineer from the uk, hoping to maybe make you laugh sometimes"
    logo = "favicon-32x32.png"

  [params.theme]
    palette = "oxocarbon"

  [params.twitter]
    creator = "hayden_dev"
    site = "hayden_dev"

  [[params.socialLinks]]
    icon = "fa-brands fa-github"
    title = "GitHub"
    url = "https://github.com/hbjydev"

  [[params.socialLinks]]
    icon = "fa-brands fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/hayden_dev"

  [[params.socialLinks]]
    icon = "fa-brands fa-twitch"
    title = "Twitch"
    url = "https://twitch.tv/hayden_dev"

  [[params.socialLinks]]
    icon = "fa-solid fa-envelope"
    title = "Email me"
    url = "mailto:hayden@kuraudo.io"

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Hayden's Home"
    subtitle = "The home of Hayden, a DevOps & Software engineer from Sheffield, UK."
    copyright = "All content in this site is available gratis under the APL2.0 license."
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Hayden's Home"
      logoHomeLink = "/"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
