baseURL = '/'
languageCode = 'en-gb'
title = "Hayden's Home"
theme = 'terminal'
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "pink"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  enableGitInfo = true

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Hayden's Home"
    subtitle = "The home of Hayden, a DevOps & Software engineer from Sheffield, UK."
    copyright = "All content in this site is available gratis under the APL2.0 license."
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Hayden's Home"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

#[module]
#  replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
#  [[module.imports]]
#    path = 'github.com/panr/hugo-theme-terminal/v3'
